---
title: "stock"
author: "Ibrahem Ali"
date: "2024-04-27"
output: html_document
---


```{r}
library(shinydashboard)
library(quantmod)
library(moments)
library(ggplot2)
library(DT)
```

```{r}
function(input, output, session){
      
    observeEvent(input$view, {close.adj=getSymbols(input$symbol, from=input$date[1],
                                                    env = NULL)
                              output$chart <- renderPlot({chartSeries(close.adj, type=input$style,
                                                                     TA=input$bb)}) 
                           }
                 )
    observeEvent(input$do, {
    session$sendCustomMessage(type = 'testmessage',
                               message = 'If API does not work, try another ticker or restart the app')
    })
    observeEvent(input$apply, {close.adj=getSymbols(input$symbol, from=input$date[1],
                                                    to=input$date[2], env = NULL)
                            output$chart <- renderPlot({chartSeries(close.adj, type=input$style, TA=input$bb
                                            )})
                                 }
                )
    observeEvent(input$view, {close.adj=getSymbols(input$symbol, from=input$date[1], to=input$date[2], env=NULL)
                              close.adj$rtn = diff(log(close.adj[, 6]))
                              output$r_chart <- renderPlot({chartSeries(close.adj$rtn)})
                              output$r_ch <- renderPlot({ggplot(data = close.adj, aes(x=close.adj$rtn)) + 
                                  geom_density(colour='green', fill='#33BF66', alpha=0.5)+theme(plot.background = 
                                  element_rect(fill='#242525'), panel.background = element_rect(fill='#292B2C'),
                                  panel.grid.minor = element_blank())+xlab('daily log_returns')+
                                  theme(axis.text=element_text(size=18, colour='#0FDD16'), axis.title=
                                  element_text(size=18, colour='#0DC22E'))
                              })
                              output$mean <- renderPrint({cat(paste(round(mean(close.adj$rtn, na.rm=TRUE),5),
                                'p-value:', round(t.test(close.adj$rtn, na.rm = TRUE)$p.value, 5), sep='\n')) })
                              output$sd <- renderPrint({sd(close.adj$rtn, na.rm=TRUE)})
                              output$skew <- renderPrint({cat(paste(round(skewness(close.adj$rtn, na.rm=TRUE),5), 'p-value:',
                                  round( 2*(pnorm( (skewness(close.adj$rtn, na.rm=TRUE))/sqrt(6/nrow(close.adj)) )),5), sep='\n'))
                                                                })
                              output$kurt <- renderPrint({cat(paste(round(kurtosis(close.adj$rtn, na.rm=TRUE),5), 'p-value:',
                                                                    round( 2*(1-pnorm( (kurtosis(close.adj$rtn, na.rm=TRUE))/sqrt(24/nrow(close.adj)) )),5), sep='\n'))
                                            })
                            }
                 )

    observeEvent(input$view, {
        sym = getSymbols(input$symbol, from=input$date[1], to=input$date[2], env = NULL)
        sym_d = data.frame(sym)
        sym_d$Date = index(sym)
        sym_d = subset(sym_d, select=c(Date, 1:6))
        output$table <- DT::renderDataTable({
        datatable(sym_d, options = list(pageLength = 16), filter='top', rownames=FALSE
                  )})
                                        })
}
```



```{r}
dashboardPage(skin='blue',
    dashboardHeader(title = 'Trader_v1.0', titleWidth = 230,
                    tags$li(a(href = 'https://www.linkedin.com/in/ibrahemalii/',
                              img(src = 'In_Logo.png',title = "linkedin link", height = "45px")),
                            class = "dropdown"),
                    tags$li(a(href = 'https://github.com/iibrahemali',
                              img(src = 'Git_Loogo.png',title = "github link", height = "45px")),
                            class = "dropdown")
                    ),
    dashboardSidebar(
        
        sidebarUserPanel("By Ihor Vodko", 
                         tags$img(src = 'pic2.jpg', width = '195', height = '100' ) 
        ),
        sidebarMenu(
            menuItem("Chart Builder", tabName = "chart", icon = icon("chart-line")),
            menuItem('Statistics', tabName='returns', icon = icon('coins')),
            menuItem("Data", tabName = "data", icon = icon("database")),
            textInput("symbol", label = "Enter a ticker (yahoo.finance)", 
                      placeholder = 'For example: AMZN'),
            actionButton('view', label = 'View'),
            tags$head(tags$script(src = "message-handler.js")),
            actionButton("do", "Read before use")
        )
    )    ,
    dashboardBody(
        tabItems(
            tabItem(tabName = "chart",
                    fluidRow(
                        column(width = 12,
                            plotOutput(outputId = "chart")
                        ),
                        column(width = 4,
                            dateRangeInput("date", label = h1('Date range'), start = '2018-01-01'),
                            actionButton('apply', 'Apply changes')
                         ),
                        column(width = 4,
                               radioButtons("bb", label = h1("Bolindger Bands"),
                                            choices = list("No" = 'NULL', "Yes" = 'addBBands(n=20, sd=2.33)'), 
                                            selected = 'NULL')
                               ),
                        column(width = 4, 
                               radioButtons('style', label=h1('Chart Style'),
                                                           choices = list('Line' = 'line', 'Bars'= 'bars', 'Candlesticks'='candlesticks' ) ,
                                                           selected = 'line'
                                            )
                               )
                )
            ),
            tabItem(tabName = "data",
                    fluidRow(box(DT::dataTableOutput("table"), width = 12))
                    ),
            tabItem(tabName = 'returns', 
                        fluidRow(
                            plotOutput(outputId = 'r_chart')
                        ),
                        fluidRow(
                          plotOutput(outputId = 'r_ch')
                          
                        ),
                        fluidRow(
                          box(width=3, title='Avg return', background='black', solidHeader=TRUE, status='warning',
                              textOutput(outputId = 'mean')
                          ),
                          box(width=3, title='Risk', background='black', solidHeader=TRUE, status='warning',
                              textOutput(outputId = 'sd')
                          ),
                          box(width = 3, title='Skewness', background='black', solidHeader=TRUE, status='warning',
                              textOutput(outputId = 'skew')
                          ),
                          box(width = 3, title='Kurtosis', background='black', solidHeader=TRUE, status='warning',
                              textOutput(outputId = 'kurt')
                          ),
                          
                        )
                    )
         )
  )
)


```

